// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Logibit.Hawk")>]
[<assembly: AssemblyDescriptionAttribute("A F# implementation of the Hawk authentication protocol. Few dependencies. No cruft.")>]
[<assembly: AssemblyVersionAttribute("6.0.2")>]
[<assembly: AssemblyFileVersionAttribute("6.0.2")>]
[<assembly: AssemblyMetadataAttribute("Commit","79d171")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Logibit.Hawk"
    let [<Literal>] AssemblyDescription = "A F# implementation of the Hawk authentication protocol. Few dependencies. No cruft."
    let [<Literal>] AssemblyVersion = "6.0.2"
    let [<Literal>] AssemblyFileVersion = "6.0.2"
    let [<Literal>] AssemblyMetadata_Commit = "79d171"
